### ISSUE TITLE
Allow for documenting title, description, and other standard OpenAPI info

### ISSUE THREAD

**Issue by aidansunbury** [aidansunbury/trpc-ui#21]
**Is your feature request related to a problem? Please describe.**
There is no way to provide documentation your entire backend, only individual procedures.

**Describe the solution you'd like**
Like swagger documentation, trpc-ui should support providing overarching documentation of the whole API, not just individual procedures. The implementation of this should follow OpenAPI standards as much as possible
![Screenshot 2024-11-08 at 9 22 31 PM](https://github.com/user-attachments/assets/c3f149f1-b979-45c4-93ac-02cf27252531)

This issue will depend on #16 being completed

**Comment by EmilMalanczak** [comment]
@aidansunbury `trpc-openapi` has undocumented `example` input / response meta property: 
 https://github.com/trpc/trpc-openapi/blob/0969818c2da30b06706cccdb27cbf54ba813ab1a/src/types.ts#L30C3-L30C14
 
 trpc-openapi typings:
 https://github.com/trpc/trpc-openapi#openapimeta
 
 what are your thoughts on adding this as well? 
 
I think that I can work on this one and add support for more properties from description above if you want some help. 
 If yes, do you have any specific requirements and/or standards?

**Comment by aidansunbury** [comment]
> @aidansunbury `trpc-openapi` has undocumented `example` input / response meta property: [trpc/trpc-openapi@`0969818`/src/types.ts#L30C3-L30C14](https://github.com/trpc/trpc-openapi/blob/0969818c2da30b06706cccdb27cbf54ba813ab1a/src/types.ts#L30C3-L30C14)
> 
> trpc-openapi typings: [trpc/trpc-openapi#openapimeta](https://github.com/trpc/trpc-openapi?rgh-link-date=2024-12-11T15%3A22%3A43Z#openapimeta)
> 
> what are your thoughts on adding this as well?
> 
> I think that I can work on this one and add support for more properties from description above if you want some help. If yes, do you have any specific requirements and/or standards?

Hey @EmilMalanczak, with this issue in particular, I am mostly referring to the info at the top of the document like a title, description, and contact. See the [info-object](https://swagger.io/specification/) in the swagger spec.

I'm going to go ahead and implement those features in a bit, however as far as metadata for individual procedures, I would love if you could create an issue outlining the specific metadata items you think would be useful. Many of them, such as assigning a path, method, or contentType, don't make that much sense for trpc-ui, but some of them may very well be useful. After you create that issue, I can assign it to you.

**Comment by EmilMalanczak** [comment]
@aidansunbury oke, I will prob sit on this in upcoming week. Will create the task and assign myself when I'll have some free time to work
