### ISSUE TITLE
Issue with tRPC Response Rendering Incorrectly

### ISSUE THREAD

**Issue by Robert-ZLF** [aidansunbury/trpc-ui#26]
**Describe the bug**
The application is not rendering the tRPC response correctly when the response format is as follows:

```
json
{
  "result": {
    "data": {
      "id": "1",
      "title": "Hello tRPC",
      "body": "..."
    }
  }
}
```
However, it does render correctly when the response includes an additional "json" key:

```
json
{
  "result": {
    "data": {
      "json": {
        "id": "1",
        "title": "Hello tRPC",
        "body": "..."
      }
    }
  }
}
```

**To Reproduce**

1. Make a tRPC request to the server.
2. Receive a response in the standard tRPC format without the "json" key.
3. Attempt to render the response in the client application.
4. Observe that the response is not rendered correctly.

**Expected behavior**
The client application should be able to render the tRPC response correctly regardless of whether the "json" key is present or not. The standard tRPC response format without the additional "json" key should be rendered as expected.

**Screenshots**
**The application is not rendering when response with “json” key**
<img width="1272" alt="image" src="https://github.com/user-attachments/assets/17251a46-bf90-4357-ad07-f32234dd4348">

**After add “json” key, it rendered correctly**
<img width="1395" alt="image" src="https://github.com/user-attachments/assets/22f2968a-bd3d-4a52-909f-8967677c5867">

**Additional context**
Example JSON Response (https://trpc.io/docs/rpc#successful-response)

**Comment by aidansunbury** [comment]
I'll get on it!
